### ISSUE TITLE
ECR Secret Operator cannnot create Secret instance in ROSA v4.17.6

### ISSUE THREAD

**Issue by h-kojima** [rh-mobb/ecr-secret-operator#18]
ECR Secret Operator cannnot create Secret instance in ROSA v4.17.6.
The following error message is output when I try to create Secret instance with the following sample YAML.
```
apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: Secret
metadata:
  name: ecr-secret-01
  namespace: test-project01
spec:
  generated_secret_name: ecr-auto-generated-secret-01
  ecr_registry: [AWS_ACCOUNT_NUMBER].dkr.ecr.us-east-2.amazonaws.com
  frequency: 10h
  region: us-east-2
```

```
Secret in version "v1alpha1" cannot be handled as a Secret: no kind "Secret" is registered for version "ecr.mobb.redhat.com/v1alpha1".
```

However, ECR Secret Operator can create Secret instance successfully in ROSA v4.16.25.
I think it seems to be embugged since ROSA v4.17.z, I would appreciate it if you could correct this issue.

Regards.
